# Yarn configuration for Sapphire UI monorepo
nodeLinker: node-modules

# Enable workspaces
enableStrictSsl: true

# Registry configuration
npmRegistryServer: "https://registry.npmjs.org/"

# Publishing configuration
npmPublishRegistry: "https://registry.npmjs.org/"

# Enable deferred versioning for workspaces
enableDeferredVersion: true

# Cache configuration
enableGlobalCache: false
